// //Components
// export { default as avatar } from './comps/avatar/avatar.vue'
// export { default as alert } from './comps/alert/alert.vue'
// export { default as breadcrumb } from './comps/breadcrumb/breadcrumb.vue'
// export { default as crumb } from './comps/breadcrumb/crumb.vue'
// export { default as button } from './comps/button/button.vue'
// export { default as card } from './comps/card/card.vue'
// export { default as chip } from './comps/chip/chip.vue'
// export { default as collapse } from './comps/collapse/collapse.vue'
// export { default as sCollapseItem } from './comps/collapse/item.vue'
// export { default as divider } from './comps/divider/divider.vue'
// export { default as dropdown } from './comps/dropdown/dropdown.vue'
// export { default as dropdownGroup } from './comps/dropdown/group.vue'
// export { default as dropdownItem } from './comps/dropdown/item.vue'
// export { default as image } from './comps/image/image.vue'
// export { default as list } from './comps/list/list.vue'
// export { default as listHeader } from './comps/list/header.vue'
// export { default as listItem } from './comps/list/item.vue'
// export { default as loader } from './comps/loader/loader.vue'
// export { default as navbar } from './comps/navbar/navbar.vue'
// export { default as navbarGroup } from './comps/navbar/group.vue'
// export { default as navbarItem } from './comps/navbar/item.vue'
// export { default as notification } from './comps/notification/notification.vue'
// export { default as pagination } from './comps/pagination/pagination.vue'
// export { default as progress } from './comps/progress/progress.vue'
// export { default as prompt } from './comps/prompt/prompt.vue'
// export { default as sidebar } from './comps/sidebar/sidebar.vue'
// export { default as sidebarGroup } from './comps/sidebar/group.vue'
// export { default as sidebarItem } from './comps/sidebar/item.vue'
// export { default as spacer } from './comps/spacer/spacer.vue'
// export { default as table } from './comps/table/table.vue'
// export { default as tableTd } from './comps/table/td.vue'
// export { default as tableTh } from './comps/table/th.vue'
// export { default as tableTr } from './comps/table/tr.vue'
// export { default as tabs } from './comps/tabs/container.vue'
// export { default as tab } from './comps/tabs/tab.vue'
// export { default as tooltip } from './comps/tooltip/tooltip.vue'

// // //Inputs
// export { default as checkbox } from './inputs/checkbox/checkbox.vue'
// export { default as datepicker } from './inputs/datepicker/datepicker.vue'
// export { default as input } from './inputs/input/input.vue'
export { default as inputColor } from './inputs/input/input-color.vue'
// export { default as inputNumber } from './inputs/input/input-number.vue'
// export { default as radio } from './inputs/radio/radio.vue'
// export { default as radioOption } from './inputs/radio/option.vue'
// export { default as select } from './inputs/select/select.vue'
// export { default as selectGroup } from './inputs/select/group.vue'
// export { default as selectOption } from './inputs/select/option.vue'
// export { default as slider } from './inputs/slider/slider.vue'
// export { default as switch } from './inputs/switch/switch.vue'
// export { default as textarea } from './inputs/textarea/textarea.vue'

// // Layouts
// export { default as col } from './layout/col/col.vue'
// export { default as row } from './layout/row/row.vue'
